import type { BranchCommunicationSettings, BranchRecord } from "@/lib/branch-types";
import {
  defaultInvoiceSettings,
  sampleMessageTemplates,
} from "@/lib/branch-communication-defaults";
import { clearedWebsiteServices } from "@/lib/branch-website-services";

const DEFAULT_HOURS = {
  monday: "09:00 – 18:00",
  tuesday: "09:00 – 18:00",
  wednesday: "09:00 – 18:00",
  thursday: "09:00 – 18:00",
  friday: "09:00 – 18:00",
  saturday: "10:00 – 16:00",
  sunday: "Closed",
};

function createBranch(partial: Omit<BranchRecord, "createdAt" | "updatedAt">): BranchRecord {
  const now = new Date().toISOString();
  return { ...partial, createdAt: now, updatedAt: now };
}

function withCommunicationDefaults(
  base: Omit<BranchCommunicationSettings, "invoice" | "messageTemplates"> & {
    invoice?: Partial<BranchCommunicationSettings["invoice"]>;
    messageTemplates?: BranchCommunicationSettings["messageTemplates"];
  },
): BranchCommunicationSettings {
  return {
    ...base,
    invoice: {
      ...defaultInvoiceSettings(base.receiptHeader || ""),
      legalName: base.receiptHeader || "",
      ...base.invoice,
    },
    messageTemplates: base.messageTemplates ?? [],
  };
}

export const DEFAULT_BRANCHES: BranchRecord[] = [
  createBranch({
    uuid: "00000000-0000-4000-8000-000000000001",
    shopId: 1,
    code: "BR-001",
    name: "Main Branch",
    type: "standard",
    status: "active",
    address: {
      line1: "12 High Street",
      line2: "",
      city: "London",
      county: "Greater London",
      postcode: "SW1A 1AA",
      country: "United Kingdom",
    },
    contact: {
      phone: "+44 20 7946 0958",
      email: "main@fonedoctors.com",
      managerName: "Faisal Sheikh",
      emergencyContact: "+44 7700 900123",
    },
    openingHours: DEFAULT_HOURS,
    holidays: [
      { id: "h1", label: "Christmas Day", date: "2026-12-25", closed: true },
      { id: "h2", label: "Boxing Day", date: "2026-12-26", closed: true },
    ],
    staff: {
      assignedStaffCount: 12,
      rolesEnabled: ["Manager", "Technician", "Cashier"],
      rotaEnabled: true,
      securityRules: "PIN required for refunds over £50",
    },
    inventory: {
      allocationMode: "dedicated",
      stockLevel: 1842,
      lowStockThreshold: 50,
      reorderRules: "Auto-reorder when below threshold",
      transferApprovalRequired: true,
      valuationMethod: "FIFO",
    },
    operations: {
      salesToday: 4280.5,
      openRepairTickets: 34,
      appointmentSlotsPerDay: 24,
      pickupEnabled: true,
      deliveryRadiusKm: 15,
      warrantyClaimsOpen: 3,
    },
    finance: {
      registerId: "REG-MAIN-01",
      cashDrawerAssigned: true,
      paymentsToday: 3920,
      refundsToday: 120,
      openInvoices: 8,
      vatRate: "20%",
      currency: "GBP",
      timezone: "Europe/London",
      endOfDayRequired: true,
    },
    online: {
      websiteVisible: true,
      marketplaceVisible: true,
      clickAndCollect: true,
      publishedProducts: 156,
      seoTitle: "Main Branch — Phone Repair London",
      repair: {
        storeRepair: true,
        postalRepair: true,
        collectMyDevice: false,
        fixAtMyAddress: false,
      },
      sellDevice: {
        sellInStore: true,
        postYourDevice: false,
        collectMyDevice: false,
      },
      buyDevice: { buyInStore: true, postMyDevice: false },
      buyAccessories: { buyInStore: true, postMyDevice: false },
      unlocking: { buyInStore: true, postMyDevice: false },
      eSim: { buyInStore: false, postMyDevice: false },
    },
    communication: withCommunicationDefaults({
      emailSender: "main@fonedoctors.com",
      smsSender: "FoneDoctors",
      receiptHeader: "Fone Doctors — Main Branch",
      receiptFooter: "Thank you for your business",
      notificationsEnabled: true,
      documentTemplate: "Standard repair receipt",
      invoice: {
        invoicePrefix: "INV-MB-",
        nextInvoiceNumber: 1042,
        paymentTerms: "net_14",
        dueDays: 14,
        showVatBreakdown: true,
        footerTerms: "Goods remain the property of Fone Doctors until paid in full.",
        defaultNotes: "All repairs include a 90-day warranty on parts and labour.",
        legalName: "Fone Doctors Main Branch Ltd",
        showBranchAddress: true,
      },
      messageTemplates: sampleMessageTemplates(),
    }),
    reporting: {
      salesTargetMonthly: 85000,
      repairTargetMonthly: 420,
      commissionRules: "5% on accessories, 2% on repairs",
      lastReportGenerated: "2026-06-12T08:00:00.000Z",
    },
    devices: {
      storageLocations: 8,
      repairShelves: 24,
      pickupAreas: 2,
      devicesInStorage: 47,
      handoverPending: 6,
    },
    system: {
      dataSyncStatus: "synced",
      lastSyncAt: new Date().toISOString(),
      franchiseOwner: "Fone Doctors HQ",
      auditLogCount: 1284,
      twoFactorRequired: true,
    },
  }),
  createBranch({
    uuid: "00000000-0000-4000-8000-000000000002",
    shopId: 1,
    code: "BR-002",
    name: "Bradford Branch",
    type: "standard",
    status: "active",
    address: {
      line1: "45 Market Street",
      line2: "Unit 3",
      city: "Bradford",
      county: "West Yorkshire",
      postcode: "BD1 1HY",
      country: "United Kingdom",
    },
    contact: {
      phone: "+44 1274 567890",
      email: "bradford@fonedoctors.com",
      managerName: "Sarah Ahmed",
      emergencyContact: "+44 7700 900456",
    },
    openingHours: DEFAULT_HOURS,
    holidays: [],
    staff: {
      assignedStaffCount: 6,
      rolesEnabled: ["Manager", "Technician"],
      rotaEnabled: true,
      securityRules: "Manager approval for voids",
    },
    inventory: {
      allocationMode: "shared",
      stockLevel: 920,
      lowStockThreshold: 30,
      reorderRules: "Weekly review",
      transferApprovalRequired: false,
      valuationMethod: "Weighted average",
    },
    operations: {
      salesToday: 2150,
      openRepairTickets: 18,
      appointmentSlotsPerDay: 16,
      pickupEnabled: true,
      deliveryRadiusKm: 10,
      warrantyClaimsOpen: 1,
    },
    finance: {
      registerId: "REG-BFD-01",
      cashDrawerAssigned: true,
      paymentsToday: 1980,
      refundsToday: 45,
      openInvoices: 3,
      vatRate: "20%",
      currency: "GBP",
      timezone: "Europe/London",
      endOfDayRequired: true,
    },
    online: {
      websiteVisible: true,
      marketplaceVisible: false,
      clickAndCollect: true,
      publishedProducts: 89,
      seoTitle: "Bradford Phone Repair",
      repair: {
        storeRepair: true,
        postalRepair: false,
        collectMyDevice: false,
        fixAtMyAddress: false,
      },
      sellDevice: {
        sellInStore: true,
        postYourDevice: false,
        collectMyDevice: false,
      },
      buyDevice: { buyInStore: false, postMyDevice: false },
      buyAccessories: { buyInStore: true, postMyDevice: false },
      unlocking: { buyInStore: false, postMyDevice: false },
      eSim: { buyInStore: false, postMyDevice: false },
    },
    communication: withCommunicationDefaults({
      emailSender: "bradford@fonedoctors.com",
      smsSender: "FoneDoctors",
      receiptHeader: "Fone Doctors — Bradford",
      receiptFooter: "Visit us again soon",
      notificationsEnabled: true,
      documentTemplate: "Standard repair receipt",
    }),
    reporting: {
      salesTargetMonthly: 42000,
      repairTargetMonthly: 220,
      commissionRules: "4% on accessories",
      lastReportGenerated: "2026-06-11T18:30:00.000Z",
    },
    devices: {
      storageLocations: 4,
      repairShelves: 12,
      pickupAreas: 1,
      devicesInStorage: 22,
      handoverPending: 2,
    },
    system: {
      dataSyncStatus: "synced",
      lastSyncAt: new Date().toISOString(),
      franchiseOwner: "Fone Doctors HQ",
      auditLogCount: 612,
      twoFactorRequired: false,
    },
  }),
  createBranch({
    uuid: "00000000-0000-4000-8000-000000000003",
    shopId: 1,
    code: "BR-003",
    name: "London Branch",
    type: "franchise",
    status: "inactive",
    address: {
      line1: "88 Oxford Street",
      line2: "",
      city: "London",
      county: "Greater London",
      postcode: "W1D 1BS",
      country: "United Kingdom",
    },
    contact: {
      phone: "+44 20 7123 4567",
      email: "london@fonedoctors.com",
      managerName: "John Smith",
      emergencyContact: "+44 7700 900789",
    },
    openingHours: { ...DEFAULT_HOURS, sunday: "11:00 – 16:00" },
    holidays: [{ id: "h3", label: "Renovation closure", date: "2026-07-01", closed: true }],
    staff: {
      assignedStaffCount: 0,
      rolesEnabled: [],
      rotaEnabled: false,
      securityRules: "—",
    },
    inventory: {
      allocationMode: "dedicated",
      stockLevel: 0,
      lowStockThreshold: 25,
      reorderRules: "Paused — branch inactive",
      transferApprovalRequired: true,
      valuationMethod: "FIFO",
    },
    operations: {
      salesToday: 0,
      openRepairTickets: 0,
      appointmentSlotsPerDay: 0,
      pickupEnabled: false,
      deliveryRadiusKm: 0,
      warrantyClaimsOpen: 0,
    },
    finance: {
      registerId: "—",
      cashDrawerAssigned: false,
      paymentsToday: 0,
      refundsToday: 0,
      openInvoices: 0,
      vatRate: "20%",
      currency: "GBP",
      timezone: "Europe/London",
      endOfDayRequired: false,
    },
    online: {
      websiteVisible: false,
      marketplaceVisible: false,
      clickAndCollect: false,
      publishedProducts: 0,
      seoTitle: "",
      ...clearedWebsiteServices(),
    },
    communication: withCommunicationDefaults({
      emailSender: "london@fonedoctors.com",
      smsSender: "FoneDoctors",
      receiptHeader: "",
      receiptFooter: "",
      notificationsEnabled: false,
      documentTemplate: "—",
    }),
    reporting: {
      salesTargetMonthly: 0,
      repairTargetMonthly: 0,
      commissionRules: "—",
      lastReportGenerated: "—",
    },
    devices: {
      storageLocations: 0,
      repairShelves: 0,
      pickupAreas: 0,
      devicesInStorage: 0,
      handoverPending: 0,
    },
    system: {
      dataSyncStatus: "pending",
      lastSyncAt: "2026-05-01T12:00:00.000Z",
      franchiseOwner: "London Franchise Ltd",
      auditLogCount: 340,
      twoFactorRequired: true,
    },
  }),
  createBranch({
    uuid: "00000000-0000-4000-8000-000000000004",
    shopId: 1,
    code: "BR-WH",
    name: "Warehouse",
    type: "warehouse",
    status: "active",
    address: {
      line1: "Unit 7 Industrial Estate",
      line2: "",
      city: "Manchester",
      county: "Greater Manchester",
      postcode: "M1 2AB",
      country: "United Kingdom",
    },
    contact: {
      phone: "+44 161 234 5678",
      email: "warehouse@fonedoctors.com",
      managerName: "Warehouse Team",
      emergencyContact: "+44 7700 900321",
    },
    openingHours: {
      ...DEFAULT_HOURS,
      saturday: "Closed",
      sunday: "Closed",
    },
    holidays: [],
    staff: {
      assignedStaffCount: 4,
      rolesEnabled: ["Inventory Manager", "Picker"],
      rotaEnabled: false,
      securityRules: "Dock access badge required",
    },
    inventory: {
      allocationMode: "shared",
      stockLevel: 12400,
      lowStockThreshold: 200,
      reorderRules: "Central procurement",
      transferApprovalRequired: true,
      valuationMethod: "FIFO",
    },
    operations: {
      salesToday: 0,
      openRepairTickets: 0,
      appointmentSlotsPerDay: 0,
      pickupEnabled: false,
      deliveryRadiusKm: 100,
      warrantyClaimsOpen: 0,
    },
    finance: {
      registerId: "—",
      cashDrawerAssigned: false,
      paymentsToday: 0,
      refundsToday: 0,
      openInvoices: 0,
      vatRate: "20%",
      currency: "GBP",
      timezone: "Europe/London",
      endOfDayRequired: false,
    },
    online: {
      websiteVisible: false,
      marketplaceVisible: false,
      clickAndCollect: false,
      publishedProducts: 0,
      seoTitle: "",
      ...clearedWebsiteServices(),
    },
    communication: withCommunicationDefaults({
      emailSender: "warehouse@fonedoctors.com",
      smsSender: "FoneDoctors",
      receiptHeader: "—",
      receiptFooter: "—",
      notificationsEnabled: false,
      documentTemplate: "Dispatch note",
    }),
    reporting: {
      salesTargetMonthly: 0,
      repairTargetMonthly: 0,
      commissionRules: "—",
      lastReportGenerated: "2026-06-10T09:00:00.000Z",
    },
    devices: {
      storageLocations: 32,
      repairShelves: 0,
      pickupAreas: 0,
      devicesInStorage: 0,
      handoverPending: 0,
    },
    system: {
      dataSyncStatus: "synced",
      lastSyncAt: new Date().toISOString(),
      franchiseOwner: "Fone Doctors HQ",
      auditLogCount: 890,
      twoFactorRequired: false,
    },
  }),
];

export function createDefaultBranchRecord(
  _legacyId: number,
  payload: {
    shopId: number;
    code: string;
    name: string;
    type: BranchRecord["type"];
    address: BranchRecord["address"];
    contact: BranchRecord["contact"];
  },
): BranchRecord {
  return createBranch({
    uuid: `default-${payload.code.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    shopId: payload.shopId,
    code: payload.code,
    name: payload.name,
    type: payload.type,
    status: "active",
    address: payload.address,
    contact: payload.contact,
    openingHours: DEFAULT_HOURS,
    holidays: [],
    staff: {
      assignedStaffCount: 0,
      rolesEnabled: ["Manager", "Technician", "Cashier"],
      rotaEnabled: false,
      securityRules: "Default store security policy",
    },
    inventory: {
      allocationMode: "dedicated",
      stockLevel: 0,
      lowStockThreshold: 25,
      reorderRules: "Manual review",
      transferApprovalRequired: true,
      valuationMethod: "FIFO",
    },
    operations: {
      salesToday: 0,
      openRepairTickets: 0,
      appointmentSlotsPerDay: 16,
      pickupEnabled: true,
      deliveryRadiusKm: 10,
      warrantyClaimsOpen: 0,
    },
    finance: {
      registerId: "",
      cashDrawerAssigned: false,
      paymentsToday: 0,
      refundsToday: 0,
      openInvoices: 0,
      vatRate: "20%",
      currency: "GBP",
      timezone: "Europe/London",
      endOfDayRequired: true,
    },
    online: {
      websiteVisible: false,
      marketplaceVisible: false,
      clickAndCollect: false,
      publishedProducts: 0,
      seoTitle: payload.name,
      ...clearedWebsiteServices(),
    },
    communication: withCommunicationDefaults({
      emailSender: payload.contact.email,
      smsSender: "FoneDoctors",
      receiptHeader: payload.name,
      receiptFooter: "Thank you",
      notificationsEnabled: true,
      documentTemplate: "Standard repair receipt",
    }),
    reporting: {
      salesTargetMonthly: 50000,
      repairTargetMonthly: 200,
      commissionRules: "Standard commission plan",
      lastReportGenerated: "—",
    },
    devices: {
      storageLocations: 2,
      repairShelves: 4,
      pickupAreas: 1,
      devicesInStorage: 0,
      handoverPending: 0,
    },
    system: {
      dataSyncStatus: "pending",
      lastSyncAt: new Date().toISOString(),
      franchiseOwner: "Fone Doctors HQ",
      auditLogCount: 0,
      twoFactorRequired: false,
    },
  });
}
