import { formatCustomerDisplayName } from "@/lib/repairs-customer-data";
import type { CustomerTableRow } from "@/types/customer-table";

function row(
  partial: Omit<CustomerTableRow, "displayName"> & { displayName?: string },
): CustomerTableRow {
  const displayName =
    partial.displayName ??
    formatCustomerDisplayName(partial.firstName, partial.lastName);
  return { ...partial, displayName };
}

export const INITIAL_CUSTOMERS: CustomerTableRow[] = [
  row({
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    phone: "+1 (555) 201-4401",
    customerGroup: "Individual",
    taxClass: "Taxable",
    city: "Boston",
    state: "MA",
    country: "United States",
    status: "active",
    createdAt: "2024-03-12T10:00:00.000Z",
    updatedAt: "2024-05-10T14:22:00.000Z",
  }),
  row({
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    phone: "+1 (555) 302-1188",
    customerGroup: "VIP",
    taxClass: "Taxable",
    city: "Cambridge",
    state: "MA",
    country: "United States",
    status: "active",
    createdAt: "2024-04-02T09:15:00.000Z",
    updatedAt: "2024-05-08T11:40:00.000Z",
  }),
  row({
    id: 3,
    firstName: "Alex",
    lastName: "Rivera",
    email: "alex.rivera@example.com",
    phone: "+1 (555) 884-2200",
    customerGroup: "Business",
    taxClass: "Non-Taxable",
    city: "Somerville",
    state: "MA",
    country: "United States",
    status: "active",
    createdAt: "2024-04-18T16:30:00.000Z",
    updatedAt: "2024-05-01T08:05:00.000Z",
  }),
  row({
    id: 4,
    firstName: "Maria",
    lastName: "Chen",
    email: "maria.chen@example.com",
    phone: "+1 (555) 771-0093",
    customerGroup: "Individual",
    taxClass: "",
    city: "Brookline",
    state: "MA",
    country: "United States",
    status: "inactive",
    createdAt: "2024-02-20T12:00:00.000Z",
    updatedAt: "2024-04-28T17:12:00.000Z",
  }),
  row({
    id: 5,
    firstName: "Sam",
    lastName: "Patel",
    email: "sam.patel@example.com",
    phone: null,
    customerGroup: "Wholesale",
    taxClass: "Exempt",
    city: "Quincy",
    state: "MA",
    country: "United States",
    status: "active",
    createdAt: "2024-05-01T08:45:00.000Z",
    updatedAt: "2024-05-15T09:30:00.000Z",
  }),
  row({
    id: 6,
    firstName: "Emily",
    lastName: "Nguyen",
    email: "emily.nguyen@example.com",
    phone: "+1 (555) 440-8821",
    customerGroup: "Individual",
    taxClass: "Taxable",
    city: "Newton",
    state: "MA",
    country: "United States",
    status: "active",
    createdAt: "2024-05-12T13:20:00.000Z",
    updatedAt: "2024-05-18T10:00:00.000Z",
  }),
];
