import type { InventoryProduct } from "@/types/inventory-product";

export const DEMO_INVENTORY_PRODUCTS: InventoryProduct[] = [
  {
    id: "prod-6999",
    numericId: 6999,
    name:
      "LCD Screen Assembly Compatible For iPhone 14 Plus (Aftermarket Plus Grade: Incell) (Lcd with Frame) (All Functionality Work Except Display Temperature Notification & Display Upgrade Notification) - Black",
    sku: "IP14P-LCD-BLK",
    barcode: "885909876543",
    category: "Mobile Parts",
    brand: "Apple",
    model: "iPhone 14 Plus",
    type: "Part",
    supplier: "Mobile Parts Co",
    valuationMethod: "FIFO",
    stock: 12,
    stockWarning: 0,
    reorderLevel: 5,
    lowStockAlert: 5,
    costPrice: 23.24,
    salePrice: 25.44,
    status: "In Stock",
    imageUrl: "/images/devices/mobile.svg",
  },
  {
    id: "prod-6998",
    numericId: 6998,
    name:
      "LCD Screen Assembly Compatible For iPhone 14 Pro Max (Aftermarket Pro: Hard OLED) (Lcd with Frame) - Black",
    sku: "IP14PM-OLED-BLK",
    barcode: "885909876544",
    category: "Mobile Parts",
    brand: "Apple",
    model: "iPhone 14 Pro Max",
    type: "Part",
    supplier: "Mobile Parts Co",
    valuationMethod: "FIFO",
    stock: 8,
    stockWarning: 1,
    reorderLevel: 4,
    lowStockAlert: 4,
    costPrice: 89.5,
    salePrice: 119.99,
    status: "In Stock",
    imageUrl: "/images/devices/mobile.svg",
  },
  {
    id: "prod-6997",
    numericId: 6997,
    name: "Battery Replacement For Samsung Galaxy S23 Ultra - OEM Grade",
    sku: "SGS23U-BAT",
    barcode: "456123789012",
    category: "Mobile Parts",
    brand: "Samsung",
    model: "Galaxy S23 Ultra",
    type: "Part",
    supplier: "PowerCell Supply",
    valuationMethod: "Weighted Average",
    stock: 3,
    stockWarning: 2,
    reorderLevel: 6,
    lowStockAlert: 6,
    costPrice: 18.75,
    salePrice: 34.99,
    status: "Low Stock",
    imageUrl: "/images/devices/mobile.svg",
  },
  {
    id: "prod-6996",
    numericId: 6996,
    name: "USB-C 20W Fast Charger — Universal White",
    sku: "USBC-20W-WHT",
    barcode: "111222333444",
    category: "Accessories",
    brand: "Generic",
    model: "Universal",
    type: "Accessory",
    supplier: "Accessory Hub",
    valuationMethod: "FIFO",
    stock: 0,
    stockWarning: 0,
    reorderLevel: 15,
    lowStockAlert: 15,
    costPrice: 4.2,
    salePrice: 12.99,
    status: "Out of Stock",
  },
  {
    id: "prod-6995",
    numericId: 6995,
    name: "iPad Air 5 Digitizer Touch Screen Assembly — Space Gray",
    sku: "IPAD-AIR5-DIG",
    barcode: "321654987111",
    category: "Tablet Parts",
    brand: "Apple",
    model: "iPad Air 5",
    type: "Part",
    supplier: "Tablet Depot",
    valuationMethod: "FIFO",
    stock: 6,
    stockWarning: 0,
    reorderLevel: 3,
    lowStockAlert: 3,
    costPrice: 42.0,
    salePrice: 69.0,
    status: "In Stock",
    imageUrl: "/images/devices/tablet.svg",
  },
];

export const FILTER_SELECT_OPTIONS = {
  categories: ["", "Mobile Parts", "Tablet Parts", "Accessories", "Phones"],
  brands: ["", "Apple", "Samsung", "Generic"],
  models: ["", "iPhone 14 Plus", "iPhone 14 Pro Max", "Galaxy S23 Ultra", "iPad Air 5", "Universal"],
  suppliers: ["", "Mobile Parts Co", "PowerCell Supply", "Accessory Hub", "Tablet Depot"],
  valuationMethods: ["", "FIFO", "Weighted Average", "LIFO"],
  criteria: ["", "Active", "Archived", "Low stock only"],
} as const;

export const PRODUCT_CATEGORIES = [
  "All",
  ...FILTER_SELECT_OPTIONS.categories.filter(Boolean),
] as const;

export const PRODUCT_TYPES = ["All", "Device", "Accessory", "Part"] as const;

export const STOCK_STATUS_FILTERS = [
  "All",
  "In Stock",
  "Low Stock",
  "Out of Stock",
  "Draft",
] as const;
